tests/e2e/Attributes.spec.ts
tests/e2e/Entitlements.spec.ts
tests/e2e/helpers/fixtures.ts
tests/e2e/helpers/operations.ts
tests/e2e/helpers/selectors.ts

Tests for Add, Delete Attribute cases

---

src/containers/Attributes/Attributes.tsx
src/containers/Attributes/CreateAttribute.tsx
src/containers/Attributes/components/CreateAttributeForm.tsx
src/hooks/useAttributes.ts

- add fetch request after attr creation;
- add components names to devtools;
- rearrange some code blocks;

Abacus 2.0: Newly added attribute doesn’t appear in the Attributes table after adding (page refresh is needed)

---

.gitignore
src/containers/Client/Client.tsx
src/containers/User/User.tsx

- add toast messages on delete action in entitlements/clients;
- update gitignore;

Abacus 2.0: Result message isn’t shown after performing Delete Entitled Attribute operation.

---

src/containers/Client/Client.tsx
src/containers/User/User.tsx

[UX] When looking at a specific user, show their username/clientname, rather than their UUID.

Show usernames and client names on respective screens

---

src/components/AttributeRule/AttributeRule.tsx
src/components/OrderCard/OrderCard.tsx
src/containers/AttributeListItem/AttributeListItem.tsx

- add rule field;
- add components' names to the devtools;

abacus does not show rule

---

src/containers/Client/AssignAttributeForm.tsx

- add display name for component;
- call reset form method;
- refactoring;

Abacus 2.0: New Attribute fields aren’t cleared after submission on Entity Details page.

---

src/containers/Attributes/components/AttributesHeader/AttributesHeader.module.css
src/containers/Attributes/components/AttributesHeader/AttributesHeader.tsx

Abacus 2.0: Authorities dropdown looks corrupted for not Logged user.

---

src/App.tsx
src/containers/Attributes/Attributes.tsx
src/hooks/useAttributes.ts
src/hooks/useAuthorities.ts
src/hooks/useFetch.ts

- add displayName to components;
- force fetch request after login;

Abacus 2.0: Page data isn’t loaded after login on custom page.

---

src/hooks/useAuthorities.ts
src/store.ts

Abacus: Custom selected authority isn’t pre-served after switching between sections.

---

src/containers/AttributeListItem/AttributeListItem.tsx

- fix fetch request and params;

Abacus 2.0: Entitlements table is blank in Attribute Detail section

---

src/containers/Attributes/components/AttributesHeader/AttributesHeader.tsx
src/containers/Attributes/components/FilterForm.tsx
tests/e2e/Attributes.spec.ts
tests/e2e/helpers/fixtures.ts
tests/e2e/helpers/selectors.ts
tests/e2e/playwright.config.ts

https://virtru.atlassian.net/browse/PLAT-1777

Playwright test for Attributes Filtering

---

src/containers/Header/Header.tsx

- fix na link active state;
- refactor code;

Abacus: Entitlements tab title isn’t highlighted when Entity Details page is opened.

---

src/containers/Attributes/components/FilterForm.tsx

Abacus: Attributes Filtering isn’t dropped on click the [Clear] button.

---

charts/abacus/templates/configmap.yaml
charts/abacus/templates/hpa.yaml
charts/abacus/templates/ingress.yaml
charts/abacus/templates/service.yaml
charts/abacus/values.yaml

- Always quote your strings, to avoid accidentally converting the empty string to nil, apparently
- follow ups for similar errors throughout the templates

🐛 Fix some helm errors

---

src/containers/Attributes/Attributes.tsx
src/containers/Attributes/CreateAttribute.tsx
src/containers/Attributes/components/CreateAuthorityForm.tsx
src/containers/Home/Home.tsx

Ticket: https://virtru.atlassian.net/browse/PLAT-1797

Abacus: Newly created authority doesn’t appear in the Authorities list w/o page reload.

---

src/containers/Header/Header.tsx

Abacus tab title remains highlighted after switching to different section.

---

src/containers/Client/AssignAttributeForm.tsx
src/containers/Entitlements/UsersTable.tsx

Abacus: Add clear placeholder text for input fields on Entity Details page.

---

src/containers/Attributes/components/AttributesHeader/AttributesHeader.module.css
src/containers/Attributes/components/AttributesHeader/AttributesHeader.tsx
src/containers/Attributes/components/FilterForm.tsx
src/store.ts

- add new field (rule) to the query store;
- add some styles;
- add badge with selected filters;

Abacus: Filtered state of the Attributes list isn’t indicated somehow. 

---

tests/e2e/Attributes.spec.ts
tests/e2e/api.spec.ts
tests/e2e/playwright.config.ts

Adjust frontend e2e test for CI

---

src/components/AutoComplete/AutoComplete.tsx
src/components/Select/Select.tsx
src/components/Select/index.ts
src/components/index.ts
src/containers/Client/AssignAttributeForm.tsx
src/containers/Client/Client.tsx
src/containers/User/User.tsx

Abacus 2.0: Authority validation isn’t performed on adding entitlement to entity (invalid item is added)

---

public/index.html

Abacus 2.0: Entity Details page remains blank after refresh.

---

package-lock.json
package.json

📄 Add license line to package.json

---

src/containers/Attributes/Attributes.tsx
src/containers/Attributes/CreateAttribute.tsx
src/store.ts

Abacus 2.0: “New” section is closed after adding new authority on the Attributes page.

---

src/containers/Attributes/CreateAttribute.tsx
src/containers/Attributes/components/CreateAttributeForm.tsx

Abacus 2.0: Subsequent empty Order field blocks attribute creation.

---

src/containers/Attributes/CreateAttribute.tsx

Abacus 2.0: 'New’ section isn’t closed on press Escape keyboard key.

---

DockerfileTests

Signed-off-by: obidenko <obidenko@virtru.com>

PLAT 1899 : fixed docker config

---

.env
README.md
package-lock.json
package.json
src/components/AttributeRule/AttributeRule.tsx
src/components/OrderCard/OrderCard.tsx
src/containers/Attributes/Attributes.tsx
src/containers/Attributes/CreateAttribute.tsx

- Fixed React warnings
- Default .env is for Quickstart
- moved craco dependency to devDependency

React warnings fix

---

src/components/OrderCard/OrderCard.tsx
src/containers/Attributes/components/CreateAttributeForm.tsx
tests/e2e/Attributes.spec.ts
tests/e2e/helpers/selectors.ts

Playwright tests for attribute with multiple order values, order editing and some more

---

package-lock.json
src/containers/Authorities/Authorities.tsx

https://virtru.atlassian.net/browse/PLAT-1897

Clean authority after removing PLAT-1897

---

tests/e2e/Attributes.spec.ts
tests/e2e/Entitlements.spec.ts
tests/e2e/api.spec.ts

Add "step" annotations to increase readability of the tests report

---

src/containers/Authorities/Authorities.tsx
tests/e2e/Attributes.spec.ts
tests/e2e/Authorities.spec.ts
tests/e2e/helpers/operations.ts
tests/e2e/helpers/selectors.ts

Playwright tests for the Authorities page

---

src/components/OrderCard/OrderCard.tsx
src/containers/AttributeListItem/AttributeListItem.tsx

PLAT 1841 ticket: ABACUS delete functionality

ABACUS Delete Button

---

src/components/OrderCard/OrderCard.tsx
src/containers/AttributeListItem/AttributeListItem.tsx
tests/e2e/Attributes.spec.ts
tests/e2e/helpers/selectors.ts

Playwright tests for Attribute removal, message corrections

---

tests/e2e/App.spec.ts
tests/e2e/Attributes.spec.ts
tests/e2e/Authorities.spec.ts
tests/e2e/Entitlements.spec.ts
tests/e2e/api.spec.ts
tests/e2e/helpers/operations.ts

Playwright tests - cleanup implementation 2

---

src/components/EditValueList/EditValueList.tsx
tests/e2e/Attributes.spec.ts
tests/e2e/helpers/selectors.ts

Playwright test for Edit order value

---

Dockerfile
server/main.go

- serves the ENV replaced index.html without writing it to disk

go server - no write file

---

src/containers/Attributes/CreateAttribute.tsx
tests/e2e/Attributes.spec.ts

Playwright tests for Attribute and Authority creation limits

---

package-lock.json
package.json

bump the version to 1.1.1. after this is merged i can tag main with a release.

PLAT-2192; 1.1.1 version bump

---

tests/e2e/App.spec.ts

Playwright tests to check proper data drop after log out on different sections

---

.github/workflows/build.yaml

https://github.com/opentdf/backend/commit/b7f081fc0f37fe998b3e67d09251e96e50cdbe45
need to do similar to the above to fix the failure: https://github.com/opentdf/frontend/actions/runs/3583224900/jobs/6029794022#step:5:16

PLAT-2239; remove deprecated set-output from workflow

---

tests/e2e/Attributes.spec.ts

Playwright tests to check proper data drop after cancelling Edit Attribute

---

package-lock.json
package.json

opentdf 1.2.0 version bump for the release.

opentdf 1.2.0 version bump 

---

src/containers/Client/ClientTable.tsx
tests/e2e/Attributes.spec.ts
tests/e2e/helpers/selectors.ts
tests/e2e/playwright.config.ts

Improvements for the Delete Entitlement Playwright test

---

.github/workflows/build.yaml
tests/e2e/App.spec.ts
tests/e2e/Attributes.spec.ts
tests/e2e/Entitlements.spec.ts
tests/e2e/helpers/operations.ts
tests/e2e/playwright.config.ts

+ switch back to 'on merge' testing trigger to align it with image creation process (inappropriate 'on PR')

Move Delete Entitlement test to improve overall test time

---

package-lock.json
package.json

version bump for 1.3.0 release
https://github.com/opentdf/frontend/pull/171 for previous

opentdf frontend 1.3.0 version bump

---

.github/workflows/build.yaml
package.json
sonar-project.properties

Sonar Code Coverage

---

package-lock.json
package.json
src/hooks/useFetch.ts
src/service/attributesAxios.ts
src/service/entitlementsAxios.ts
src/service/keycloakAxios.ts

Update to axios
- https://github.com/opentdf/frontend/pull/210

axios 1.6.2

---

vite.config.ts

https://vitejs.dev/config/server-options.html

PLAT-3068 Allow any host not just localhost
